### ISSUE TITLE
Error: undefined symbol: sqlite3_sqliteulid_init

### ISSUE THREAD

**Issue by Kingsley-Eghianruwa** [asg017/sqlite-ulid#7]
i compiled sqlite_ulid using ```cargo build -r --target aarch64-linux-android``` . i get the libsqlite_ulid.so file.i assume this file is a loadable sqlite extension but when i try to load the extension via ```.load ./libsqlite_ulid``` , i get the error ```Error: undefined symbol: sqlite3_sqliteulid_init```. please how do i resolve this or how do i build a loadable extension for android

**Comment by asg017** [comment]
Try renaming the `libsqlite_ulid.so` file to `ulid.so` and try again, with `.load ./ulid`.

Alternatively, try `.load ./libsqlite_ulid sqlite3_ulid_init`

This is happening because the entrypoint is named `sqlite3_ulid_init`, and sqlite [tries to guess the entrypoint](https://www.sqlite.org/loadext.html#:~:text=Both%20methods%20for,be%20called%20%22sqlite3_spellfixext_init%22.) based on the name of the extension file. So it either needs to be called `ulid.so` (or `ulid0.so`), or you can instead pass in the entrypoint name manually.

**Comment by Kingsley-Eghianruwa** [comment]
Thank you. both suggestions worked.
